# Generated by Django 4.1.5 on 2023-01-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_outsideproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='outsideProduct',
            new_name='amazonlink',
        ),
    ]
