# Generated by Django 4.1.5 on 2023-01-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_outsideproduct_amazonlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonlink',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
