# Generated by Django 4.1.5 on 2023-01-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_amazonlink_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonlink',
            name='share',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
