name: Django CI/CD with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose --version

    - name: Build and Run Containers with Docker Compose
      run: docker-compose up -d

    - name: Run Django Tests
      run: docker exec ecommerce-web python manage.py test

    # Add additional steps for linting, migrations, or other required actions

    # Optional: Push the Docker image to a registry (like Docker Hub)

    - name: Stop and Remove Containers
      run: docker-compose down




